import type { Metadata } from "next";
import { Geist, Roboto_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
    variable: "--font-roboto-mono",
    subsets: ["latin"],
    fallback: ["monospace"],
});

export const metadata: Metadata = {
    title: "Codertype",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={cn(jetbrainsMono.variable, "font-mono")} >
            <body
                className={`${robotoMono.variable} font-mono antialiased dark`}
            >
                {children}
            </body>
        </html>
    );
}
