import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";

const jetbrainsMono = JetBrains_Mono({
    subsets: ["latin"],
    variable: "--font-mono",
    fallback: ["monospace"],
});

export const metadata: Metadata = {
    title: "Codertype",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={cn(jetbrainsMono.variable)}>
            <body className="font-mono antialiased dark min-h-screen flex flex-col">
                <Navbar />
                {children}
            </body>
        </html>
    );
}
